version: '3'

services:
  flowise:
    image: flowiseai/flowise:latest
    container_name: flowise
    ports:
      - "3000:3000"
    volumes:
      - ./storage:/root/.flowise
    environment:
      - PORT=3000
      - APIKEY_PATH=/root/.flowise
    restart: unless-stopped